# github token key : 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

server:
  port: 8081
  
--- 

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:sqlite:sqliteLocal.db
    driver-class-name: org.sqlite.JDBC
  
logging:
  level:
    root: info
    
