# github token key : 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

server:
  port: 8081
  
--- 

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:sqlite:sqliteLocal.db
    driver-class-name: org.sqlite.JDBC
  
logging:
  level:
    root: info
    
